<?php
?>

<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php $helper = $this->helper(\Instant\Checkout\Helper\Data::class); ?>
<?php $formId = $helper->getProductPageAddToCartFormId(); ?>

<!-- INSTANT BUTTON START -->
<div id="checkout-index-instant-btn-container" class="instant-btn-container">
    <fieldset class="instant-btn-wrapper">
        <legend class="instant-buy-one-tap">Buy in 1-tap</legend>
        <button id="checkout-index-page-instant-btn" type="button" title="Instant Checkout" class="instant-btn" data-mage-init='
                    {
                        "Instant_Checkout/js/checkout-index-page-checkout": {}            
                    }
                    '>
            <div id="checkout-index-page-instant-btn-loading-indicator" class='instant-btn-loading'></div>
            <svg id="checkout-index-page-instant-btn-lock-icon" xmlns="http://www.w3.org/2000/svg" width="17" height="15" style="margin-right:7px;" viewBox="0 0 22 22">
                <path style="fill:white" d="M18 10v-4c0-3.313-2.687-6-6-6s-6 2.687-6 6v4h-3v14h18v-14h-3zm-10 0v-4c0-2.206 1.794-4 4-4s4 1.794 4 4v4h-8z" />
            </svg>
            <span id="checkout-index-page-instant-btn-text">Instant Checkout</span>
        </button>
        <div id="checkout-index-page-instant-backdrop" class="instant-backdrop">
            <h4 id="checkout-index-page-back-to-checkout" class="instant-back-to-checkout">Back to checkout</h4>
        </div>
    </fieldset>
    <div class="instant-strike">
        <span>or</span>
    </div>
</div>
<!-- INSTANT BUTTON END -->