<?php
?>

<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php $helper = $this->helper(\Instant\Checkout\Helper\Data::class); ?>
<?php $formId = $helper->getProductPageAddToCartFormId(); ?>
<!-- INSTANT BUTTON START -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">

<div class='instant-reset-css'>
    <div id="checkout-index-instant-btn-container" class="instant-btn-container">
        <fieldset class="minicart-instant-btn-wrapper">
            <legend class="instant-skip-the-forms" align="center">Skip the forms</legend>
            <div class="flex-inner-wrapper">
                <button id="checkout-index-page-instant-btn" type="button" title="Instant Checkout" class="instant-btn" data-mage-init='
                    {
                        "Instant_Checkout/js/checkout-index-page-checkout": {}            
                    }
                    '>
                    <div id="checkout-index-page-instant-btn-loading-indicator" class='instant-btn-loading'></div>
                    <svg id="checkout-index-page-instant-btn-lock-icon" xmlns="http://www.w3.org/2000/svg" width="17" height="15" style="margin-right:7px" viewBox="0 0 22 22">
                        <path style="fill:white" d="M18 10v-4c0-3.313-2.687-6-6-6s-6 2.687-6 6v4h-3v14h18v-14h-3zm-10 0v-4c0-2.206 1.794-4 4-4s4 1.794 4 4v4h-8z" />
                    </svg>
                    <span id="checkout-index-page-instant-btn-text">Instant Checkout</span>
                </button>
                <div id="desktop-checkout-index-page-instant-backdrop" class="instant-backdrop">
                    <h4 id="desktop-checkout-index-page-back-to-checkout" class="instant-back-to-checkout">Back to checkout</h4>
                </div>
                <div id="mobile-checkout-index-page-instant-backdrop" class="instant-backdrop">
                    <div class="mobile-instant-back-to-checkout-backdrop-inner-container">
                        <div class="mobile-instant-back-to-checkout-text">Finish reviewing your order</div>
                        <div class="mobile-instant-back-to-checkout-text">or</div>
                        <div id="mobile-checkout-index-page-back-to-checkout" class="mobile-instant-back-to-shopping-text">Go back to shopping</div>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="instant-strike">
            <span>or</span>
        </div>
    </div>
</div>
<!-- INSTANT BUTTON END -->