<?php
?>

<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php $helper = $this->helper(\Instant\Checkout\Helper\InstantHelper::class); ?>
<!-- INSTANT BUTTON START -->
<div id="ic-cindex-btn-container" class="ic-btn-container">
    <div class='ic-css-reset'>
        <div id="ic-cindex-btn-wrapper" class="ic-btn-wrapper">
            <button disabled id="ic-cindex-btn" type="button" title="Instant Checkout" class="ic-btn" data-mage-init='
                    {
                        "Instant_Checkout/js/ic-cindex-checkout": {
                            "shouldResizeCartIndexBtn": "<?= $block->escapeHtml($helper->getShouldResizeCartIndexBtn()) ?>",
                            "btnBorderRadius": "<?= $block->escapeHtml($helper->getBtnBorderRadius()) ?>",
                            "btnHeight": "<?= $block->escapeHtml($helper->getBtnHeight()) ?>",
                            "btnColor": "<?= $block->escapeHtml($helper->getBtnColor()) ?>",
                            "baseCurrencyCode": "<?= $block->escapeHtml($helper->getBaseCurrencyCode()) ?>",
                            "currentCurrencyCode": "<?= $block->escapeHtml($helper->getCurrentCurrencyCode()) ?>"
                        }            
                    }
                    '>
                <svg id="ic-cindex-btn-lock-icon" xmlns="http://www.w3.org/2000/svg" width="17" height="15" style="margin-right:7px" viewBox="0 0 22 22">
                    <path style="fill:white" d="M18 10v-4c0-3.313-2.687-6-6-6s-6 2.687-6 6v4h-3v14h18v-14h-3zm-10 0v-4c0-2.206 1.794-4 4-4s4 1.794 4 4v4h-8z" />
                </svg>
                <span id="ic-cindex-btn-text">Instant Checkout</span>
            </button>
            <div id="ic-cindex-btn-strike" class="ic-btn-strike">
                <span>or</span>
            </div>
        </div>
    </div>
</div>
<!-- INSTANT BUTTON END -->