<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<div id="ic-pdp-btn-container" class="ic-btn-container" style="display: none">
    <div id="ic-pdp-btn-wrapper" class="ic-btn-wrapper">
        <div id="ic-pdp-btn"
            data-instant-hascustomoptions="<?= $block->getProductHasCustomOptions() ? 'true' : 'false' ?>"
            data-instant-productsku="<?= $block->escapeHtmlAttr($block->getProduct()->getSku()) ?>"
            data-instant-producttype="<?= $block->escapeHtmlAttr($block->getProduct()->getTypeId()) ?>" type="button"
            data-instant="true">
        </div>
        <div id="ic-pdp-btn-strike" class="ic-btn-strike">
            <span>or</span>
        </div>
    </div>
</div>