<?php
?>

<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php $helper = $this->helper(\Instant\Checkout\Helper\InstantHelper::class); ?>

<div id="ic-pdp-btn-container" class="ic-btn-container">
    <div class='ic-css-reset'>
        <div id="ic-pdp-btn-wrapper" class="ic-btn-wrapper" style="margin-top:0px !important;">
            <button id="ic-pdp-btn" hasCustomOptions="<?= $block->getProductHasCustomOptions() ? 'true' : 'false' ?>" sku="<?= $block->escapeHtmlAttr($block->getProduct()->getSku()) ?>" type="<?= $block->escapeHtmlAttr($block->getProduct()->getTypeId()) ?>" style="" type="button" title="Instant Checkout" class="ic-btn" data-instant="true" data-mage-init='
            {
                "Instant_Checkout/js/ic-pdp-checkout": {
                    "sku": "<?= $block->escapeHtmlAttr($block->getProduct()->getSku()) ?>",
                    "shouldResizePdpBtn": "<?= $block->escapeHtml($helper->getShouldResizePdpBtn()) ?>",
                    "shouldPositionPdpBelowAtc": "<?= $block->escapeHtml($helper->getShouldPositionPdpBelowAtc()) ?>",
                    "pdpBtnCustomStyle": "<?= $block->escapeHtml($helper->getPdpBtnCustomStyle()) ?>",
                    "pdpBtnContainerCustomStyle": "<?= $block->escapeHtml($helper->getPdpBtnContainerCustomStyle()) ?>",
                    "pdpBtnRepositionDiv": "<?= $block->escapeHtml($helper->getPdpBtnRepositionDiv()) ?>",
                    "pdpBtnRepositionWithinDiv": "<?= $block->escapeHtml($helper->getPdpBtnRepositionWithinDiv()) ?>",
                    "pdpShouldRepositionOrStrikeAboveBtn": "<?= $block->escapeHtml($helper->getShouldRepositionOrStrikeAbovePdpBtn()) ?>"
                }            
            }
            '>
                Instant Checkout
            </button>
            <div id="ic-pdp-btn-strike" class="ic-btn-strike">
                <span>or</span>
            </div>
        </div>
    </div>
</div>