<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">

<div id='ic-backdrop-container' class='ic-css-reset'>
    <div class='ic-backdrop-close'>✕</div>
    <div id="ic-backdrop" class="ic-backdrop">
        <div class="ic-backdrop-content">
            <h4 id="ic-backdrop-message" class="ic-backdrop-message">Don't see your secure checkout window? We'll help you re-launch the window to complete your purchase.</h4>
            <h4 id="ic-backdrop-continue" class="ic-backdrop-continue">Click to Continue</h4>
        </div>
    </div>
</div>