<?php

/**
 * Instant_Checkout
 *
 * @package   Instant_Checkout
 * @author    Instant <hello@instant.one>
 * @copyright 2022 Copyright Instant. https://www.instantcheckout.com.au/
 * @license   https://opensource.org/licenses/OSL-3.0 OSL-3.0
 * @link      https://www.instantcheckout.com.au/
 */

declare(strict_types=1);

use Instant\Checkout\Block\Adminhtml\System\Config\Activation\Send;

/** @var Send $block */
?>
<script>
    require(['prototype'], function() {
        const params = <?= $block->getPostParams() ?>;
        const activationMessage = $('activation_result');

        function activateSend() {
            jQuery.ajax({
                    url: '<?= $block->getAjaxUrl() ?>',
                    data: JSON.stringify(params),
                    processData: false,
                    dataType: "json",
                    contentType: "application/json",
                    method: 'POST',
                    beforeSend: () => {},
                })
                .done((response) => {
                    jQuery.ajax({
                            url: '/index.php/rest/V1/instant/set-merchant-and-token',
                            data: JSON.stringify({
                                'merchantId': response['merchantId'],
                                'accessToken': response['accessToken'],
                            }),
                            processData: false,
                            dataType: "json",
                            contentType: "application/json",
                            method: 'POST',
                            beforeSend: () => {},
                        })
                        .done((response) => showSuccessMessage())
                        .error((error) => showErrorMessage(error?.responseJSON?.message));
                }).fail((error) => {
                    showErrorMessage(error?.responseJSON?.message);
                });
        }

        function showSuccessMessage() {
            activationMessage.update('Activation was successful!');
            activationMessage.removeClassName('hidden').removeClassName('admin__field-error').addClassName('note');
            activationMessage.setStyle({
                color: 'green'
            });
        }

        function showErrorMessage(errorMessage) {
            const msg = "Contact help@instant.one if you keep seeing this error.";
            activationMessage.update('Error: ' + errorMessage + `<br /><br /> ${msg}` ?? `An error occurred. ${msg}`);
            activationMessage.removeClassName('hidden').addClassName('admin__field-error');
            activationMessage.removeClassName('hidden').addClassName('admin__field-error');
        }

        window.activateSend = activateSend;
    });
</script>

<div class="actions actions-activation-send">
    <p class="admin__field-error hidden" id="activation_result" style="margin-bottom:10px;"></p>
    <button onclick="activateSend(); return false;" class="action-activate-send" type="button" id="<?= /* @noEscape */
                                                                                                    $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>