<?php

/**
 * Instant_Checkout
 *
 * @package   Instant_Checkout
 * @author    Instant <hello@instant.one>
 * @copyright 2022 Copyright Instant. https://www.instantcheckout.com.au/
 * @license   https://opensource.org/licenses/OSL-3.0 OSL-3.0
 * @link      https://www.instantcheckout.com.au/
 */

declare(strict_types=1);

use Instant\Checkout\Block\Adminhtml\System\Config\Activation\Send;

/** @var Send $block */
?>
<script>
    require(['prototype'], function() {
        function activateSend() {
            const params = <?= $block->getPostParams() ?>;
            const activationMessage = $('activation_result');

            new Ajax.Request('<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>', {
                parameters: params,
                method: 'POST',
                onSuccess: function(response) {
                    console.log("Response is", response);

                    new Ajax.Request('/V1/instant/set_app_id_and_access_token', {
                        parameters: {
                            'appId': 'some app id',
                            'accessToken': 'testing123',
                        },
                        method: 'POST',
                        onSuccess: function(response) {
                            console.log("Post request sent! Response is:", response);
                        }
                    });

                    var result = '<?= $block->escapeJs($block->escapeHtml(__('Error during Activation.'))) ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                        }
                        if (response.valid == 1) {
                            activationMessage.removeClassName('hidden').removeClassName('admin__field-error').addClassName('note');
                            activationMessage.setStyle({
                                color: 'green'
                            });
                            result = 'Activation Success';
                        } else {
                            activationMessage.removeClassName('hidden').addClassName('admin__field-error');
                        }
                    } catch (e) {
                        activationMessage.removeClassName('hidden').addClassName('admin__field-error');
                    }
                    activationMessage.update(result);
                }
            });
        }
        window.activateSend = activateSend;
    });
</script>
<div class="actions actions-activation-send">
    <p class="admin__field-error hidden" id="activation_result" style="margin-bottom:10px;"></p>
    <button onclick="activateSend(); return false;" class="action-activate-send" type="button" id="<?= /* @noEscape */
                                                                                                    $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>